### ISSUE TITLE
My event repeat continuously

### ISSUE THREAD

**Issue by cuong96** [kiepng/Unity-PullToRefresh#1]
Hello! Thanks for great package. But i have problem, that is my event in OnRefresh, it repeat repeatedly rather than calling once.
![issue](https://user-images.githubusercontent.com/47582910/52768378-edbb1d00-305f-11e9-83d1-a07272daef23.png)
Thanks for reading this and sorry about my bad English

**Comment by mtakada16** [comment]
Hi, @cuong96  . Thanks for reporting the issue!

This problem is solved. Please update the package to v1.0.1.

Thanks.
